
# Adder

/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/insert adder
/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/insert readout
/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/readout/setDepth 3

# Crystal Blurring
# assign a different energy resolution for each crystal in the detector block
/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/insert energyResolution
/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/energyResolution/fwhm 0.21
/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV

#/gate/digitizerMgr/name Singles_2
/gate/digitizerMgr/chooseSD layerGSO13
#/gate/digitizerMgr/insert SinglesDigitizer
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_2/insert systemFilter
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_2/systemFilter/selectSystem scanner3
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_2/insert adder
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_2/insert readout
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_2/readout/setDepth 2

#/gate/digitizerMgr/name Singles_3
/gate/digitizerMgr/chooseSD layerGSO13
#/gate/digitizerMgr/insert SinglesDigitizer
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_3/insert systemFilter
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_3/systemFilter/selectSystem scanner4
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_3/insert adder
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_3/insert readout
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_3/readout/setDepth 2


# READOUT
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/insert readout
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/readout/setDepth 2

# Crystal Blurring
# assign a different energy resolution for each crystal in the detector block
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/insert energyResolution
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/energyResolution/fwhm 0.099
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/energyResolution/energyOfReference 511. keV

/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_3/insert efficiency
/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles_3/efficiency/setUniqueEfficiency 0.9058
#QE: probability for the event to be detected by the photo-detector.


# THRESHOLDER / UPHOLDER
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/insert energyFraming
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/energyFraming/setMin 0.0 keV
#/gate/digitizerMgr/layerGSO13/SinglesDigitizer/Singles/energyFraming/setMax  10000.0 keV
