
# ASCII
#/gate/output/ascii/disable
#/gate/output/ascii/setOutFileHitsFlag 0
#/gate/output/ascii/setOutFileSinglesFlag 0
#/gate/output/ascii/setOutFileCoincidencesFlag 0

# ROOT
/gate/output/root/enable
/gate/output/root/setFileName output
/gate/output/root/setRootNtupleFlag 0
/gate/output/root/setRootHitFlag 0
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setSaveRndmFlag 1
/gate/random/verbose 1


# LMF
#/gate/output/lmf/disable
