#################################################################
# shieldingY1
/gate/world/daughters/name shieldingY1
/gate/world/daughters/insert box
/gate/shieldingY1/geometry/setXLength   28.88  mm
/gate/shieldingY1/geometry/setYLength   10.0  mm
/gate/shieldingY1/geometry/setZLength   204.0  mm
/gate/shieldingY1/placement/setTranslation 112.44 31.88 0. mm
/gate/shieldingY1/setMaterial Lead
/gate/shieldingY1/vis/setColor gray
/gate/shieldingY1/vis/forceSolid
/gate/shieldingY1/vis/setVisible 1

#Repeat Module
/gate/shieldingY1/repeaters/insert ring
/gate/shieldingY1/ring/setRepeatNumber 1

#################################################################
# shieldingY2
/gate/world/daughters/name shieldingY2
/gate/world/daughters/insert box
/gate/shieldingY2/geometry/setXLength   28.88  mm
/gate/shieldingY2/geometry/setYLength   10.0  mm
/gate/shieldingY2/geometry/setZLength   204.0  mm
/gate/shieldingY2/placement/setTranslation 112.44 -31.88 0. mm
/gate/shieldingY2/setMaterial Lead
/gate/shieldingY2/vis/setColor gray
/gate/shieldingY2/vis/forceSolid
/gate/shieldingY2/vis/setVisible 1

#Repeat Module
/gate/shieldingY2/repeaters/insert ring
/gate/shieldingY2/ring/setRepeatNumber 1